import { describe, it, expect } from 'vitest';
import {
  createViaMcpClient,
  signRequest,
  ViaMcpAuthError,
} from '../src/mcp/client.js';

const URL = 'https://mcp.example.test/mcp';
const API_KEY = 'e7b1c0de-0000-4000-8000-abcdefabcdef';
const SECRET = 'signing-secret';

/** A fetch double that records what was sent and replays a canned JSON-RPC response. */
function stubFetch(reply: unknown, init: { status?: number; headers?: Record<string, string> } = {}) {
  const seen: { body: string; headers: Record<string, string> }[] = [];
  const impl = (async (_url: string, opts: { body: string; headers: Record<string, string> }) => {
    seen.push({ body: opts.body, headers: opts.headers });
    return {
      ok: (init.status ?? 200) < 400,
      status: init.status ?? 200,
      headers: { get: (k: string) => init.headers?.[k.toLowerCase()] ?? null },
      json: async () => reply,
    };
  }) as unknown as typeof fetch;
  return { impl, seen };
}

describe('the VIA MCP client — journey A4', () => {
  describe('the signature is a wire contract', () => {
    it('matches a vector generated by the PLATFORM implementation', () => {
      // Produced by @humanos/crypto's generateSignature — the function apps/mcp verifies with.
      // If either side ever changes how it derives the HMAC, this fails instead of a live request
      // failing with an error that looks like a bad credential.
      const body = JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'tools/list' });
      expect(signRequest(body, 'golden-secret', 1757160000000)).toBe(
        'f7a8074de721ee70b3e10b608bebc1525104bbca35fbc9846cc6aeb408830cc4',
      );
    });

    it('signs the timestamp ALONE when the body is empty', () => {
      expect(signRequest('', 'golden-secret', 1757160000000)).toBe(
        'acb6b889636f5befc590317a2bdbaf93a0f741697f66d68d32470a6ffd24bf19',
      );
    });

    it('sends the EXACT bytes it signed', async () => {
      const { impl, seen } = stubFetch({ result: { tools: [] } });
      const client = createViaMcpClient({ url: URL, apiKey: API_KEY, signatureSecret: SECRET, fetchImpl: impl, now: () => 1757160000000 });
      await client.listTools();

      // Re-serialising for the request instead of reusing the signed string is the classic way an
      // SDK produces signatures that verify locally and fail on the wire.
      const { body, headers } = seen[0]!;
      expect(headers['x-signature']).toBe(signRequest(body, SECRET, 1757160000000));
      expect(headers['x-timestamp']).toBe('1757160000000');
      expect(headers.Authorization).toBe(`Bearer ${API_KEY}`);
      expect(headers.Accept).toContain('text/event-stream');
    });
  });

  describe('talking to the connector', () => {
    it('lists tools', async () => {
      const { impl } = stubFetch({ result: { tools: [{ name: 'via_list_agents' }] } });
      const client = createViaMcpClient({ url: URL, apiKey: API_KEY, signatureSecret: SECRET, fetchImpl: impl });
      expect((await client.listTools()).map((t) => t.name)).toEqual(['via_list_agents']);
    });

    it('returns a tool result as text', async () => {
      const { impl } = stubFetch({ result: { content: [{ type: 'text', text: '{"ok":true}' }] } });
      const client = createViaMcpClient({ url: URL, apiKey: API_KEY, signatureSecret: SECRET, fetchImpl: impl });
      const out = await client.callTool('via_server_info');
      expect(out).toEqual({ text: '{"ok":true}', isError: false });
    });

    it('surfaces a REFUSAL as a result, not a thrown error', async () => {
      // A refusal means the request was understood and denied — final. Throwing would invite a
      // retry loop against a decision that will never change.
      const { impl } = stubFetch({ result: { content: [{ type: 'text', text: 'No agent did:key:zX …' }], isError: true } });
      const client = createViaMcpClient({ url: URL, apiKey: API_KEY, signatureSecret: SECRET, fetchImpl: impl });
      const out = await client.callTool('via_get_events', { did: 'did:key:zX' });
      expect(out.isError).toBe(true);
      expect(out.text).toContain('No agent');
    });

    it('throws on a JSON-RPC error, which is NOT a refusal', async () => {
      const { impl } = stubFetch({ error: { code: -32601, message: 'method not found' } });
      const client = createViaMcpClient({ url: URL, apiKey: API_KEY, signatureSecret: SECRET, fetchImpl: impl });
      await expect(client.callTool('nope')).rejects.toThrow(/method not found/);
    });

    it('raises ViaMcpAuthError on a 401 and carries the challenge', async () => {
      const { impl } = stubFetch({}, {
        status: 401,
        headers: { 'www-authenticate': 'Bearer error="invalid_token", resource_metadata="https://mcp.example.test/.well-known/oauth-protected-resource"' },
      });
      const client = createViaMcpClient({ url: URL, apiKey: API_KEY, signatureSecret: SECRET, fetchImpl: impl });
      const err = await client.listTools().catch((e) => e);
      expect(err).toBeInstanceOf(ViaMcpAuthError);
      // The challenge names where to authenticate — the only useful thing in an empty refusal.
      expect(err.message).toContain('resource_metadata');
    });
  });
});
